.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-b 1  "git-b 1.5.0" 
.SH NAME
git\-b \- Fuzzy git branch picker.
.SH SYNOPSIS
\fBgit\-b\fR [\fB\-b \fR] [\fB\-\-no\-color\fR] [\fB\-\-color\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIBRANCH\fR] 
.SH DESCRIPTION
Interactive fuzzy finder for git branches, sorted by recent commit date.
.PP
Without arguments, opens a picker to choose a branch. With a branch name, checks out the first fuzzy match. Use \-b to create and checkout a new branch.
.SH OPTIONS
.TP
\fB\-b\fR \fI<NEW_BRANCH>\fR
Create and checkout a new branch (git checkout \-b)
.TP
\fB\-\-no\-color\fR
Disable colored branch listing in the picker
.TP
\fB\-\-color\fR \fI<NAME:HASH:SUBJECT>\fR
Set field colors as NAME:HASH:SUBJECT (e.g. cyan:yellow:white)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIBRANCH\fR]
Branch name to fuzzy\-match and checkout directly (skips the picker)
.SH VERSION
v1.5.0
.SH AUTHORS
Joseph Harrison\-Lim <josephharrisonlim@gmail.com>
