#!/usr/bin/env bash

set -e

name="git-b"
version="$1"

mac_intel="x86_64-apple-darwin"
mac_silicon="aarch64-apple-darwin"
linux_intel="x86_64-unknown-linux-gnu"

mac_intel_tar="$name-v$version-$mac_intel.tar.gz"
mac_silicon_tar="$name-v$version-$mac_silicon.tar.gz"
linux_intel_tar="$name-v$version-$linux_intel.tar.gz"

package_tarball() {
  local target="$1"
  local tarball="$2"
  local staging
  staging=$(mktemp -d)

  mkdir -p "$staging/share/man/man1"
  cp "target/$target/release/$name" "$staging/"
  cp "man/git-b.1" "$staging/share/man/man1/"

  tar -czvf "$tarball" -C "$staging" .
  rm -rf "$staging"
}

# Release build runs build.rs, which writes man/git-b.1
cargo build --target=$mac_intel --release
cargo build --target=$mac_silicon --release
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc \
  cargo build --target=$linux_intel --release

if [[ ! -f man/git-b.1 ]]; then
  echo "error: man/git-b.1 not found (expected from build.rs)" >&2
  exit 1
fi

package_tarball "$mac_silicon" "$mac_silicon_tar"
silicon_sha=$(shasum -a 256 "$mac_silicon_tar" | cut -d ' ' -f 1)

package_tarball "$mac_intel" "$mac_intel_tar"
intel_sha=$(shasum -a 256 "$mac_intel_tar" | cut -d ' ' -f 1)

package_tarball "$linux_intel" "$linux_intel_tar"

sed -i '' -e "s|X86_64_SHA\ \=.*|X86_64_SHA = '$intel_sha'|" Formula/git-b.rb
sed -i '' -e "s|AARCH64_SHA\ \=.*|AARCH64_SHA = '$silicon_sha'|" Formula/git-b.rb
sed -i '' -e "s|VERSION\ \=.*|VERSION = '$version'|" Formula/git-b.rb
